# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            生数
tagline:          'anything related to math and biology'
description:      'This blog is dedicated to exploring all the possible connections between the world of mathematics and biology' 
url:              jwang123.github.io
baseurl:          /

author:
  name:           'Jerry Wang'
  url:            jwang123.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           jwang123.github.io

# Gems
gems: [jekyll-paginate]