# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Life and patterns
tagline:          '--'
description:      'Exploring the patterns of the living world with the language of mathematics'
url:              jwang123.github.io
baseurl:          /

author:
  name:           'Jerry Wang'
  url:            jwang123.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           jwang123.github.io

# Gems
gems: [jekyll-paginate]
